### ISSUE TITLE
Not able to Share Project Update

### ISSUE THREAD

**Issue by rahulranjanmca** [topcoderinc/connect-test-cycle-1#175]
### Reported URL ###

https://connect.topcoder-dev.com/projects/2587/

### Reproduction Steps ###
1. Create Project with login / without login
2. Go to Project Page
3. Try to share project update

### Expected Result ###
Should be able to post project update to team.

### Actual  Result ##
It shows error "Failed to create topic in Discourse: Unable to create discourse user".

### Screenshots ###
<img width="1668" alt="screen shot 2018-02-18 at 10 14 18 am" src="https://user-images.githubusercontent.com/1094805/36348585-c7f8cc68-1498-11e8-9765-245863cf4410.png">

### Issue Information ###

Frequency: Every time for this project

Device: Mac Pro 2017

OS: High Seira

Browser: Mac Safari Version 11.0.2

**Comment by sdgun** [comment]
```
POST https://api.topcoder-dev.com/v4/topics/ 500 ()
main.e781634f18736872f4b2.js:35 Uncaught (in promise) Error: Request failed with status code 500
    at e.exports (https://connect.topcoder-dev.com/main.e781634f18736872f4b2.js:35:191905)
    at e.exports (https://connect.topcoder-dev.com/main.e781634f18736872f4b2.js:67:83600)
    at XMLHttpRequest.p.(anonymous function) (https://connect.topcoder-dev.com/main.e781634f18736872f4b2.js:35:191052)
e.exports @ main.e781634f18736872f4b2.js:35
e.exports @ main.e781634f18736872f4b2.js:67
p.(anonymous function) @ main.e781634f18736872f4b2.js:35
Promise.then (async)
(anonymous) @ main.e781634f18736872f4b2.js:67
dispatch @ main.e781634f18736872f4b2.js:62
(anonymous) @ main.e781634f18736872f4b2.js:52
(anonymous) @ main.e781634f18736872f4b2.js:62
(anonymous) @ main.e781634f18736872f4b2.js:67
(anonymous) @ main.e781634f18736872f4b2.js:62
value @ main.e781634f18736872f4b2.js:129
value @ main.e781634f18736872f4b2.js:16
r @ main.e781634f18736872f4b2.js:21
a @ main.e781634f18736872f4b2.js:21
s @ main.e781634f18736872f4b2.js:21
p @ main.e781634f18736872f4b2.js:16
m @ main.e781634f18736872f4b2.js:16
r @ main.e781634f18736872f4b2.js:35
processEventQueue @ main.e781634f18736872f4b2.js:16
r @ main.e781634f18736872f4b2.js:62
handleTopLevel @ main.e781634f18736872f4b2.js:62
i @ main.e781634f18736872f4b2.js:62
perform @ main.e781634f18736872f4b2.js:16
batchedUpdates @ main.e781634f18736872f4b2.js:62
i @ main.e781634f18736872f4b2.js:16
dispatchEvent @ main.e781634f18736872f4b2.js:62
5main.e781634f18736872f4b2.js:129 
```

**Comment by sdgun** [comment]
https://github.com/topcoderinc/connect-test-cycle-1/issues/95
