### ISSUE TITLE
User unable to post Same comment in discussion as New Reply

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#215]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/591/discussions/2324

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_copilot/topcoder123
2. Navigate to Discussion of any Active/Completed  project like https://connect.topcoder-dev.com/projects/591/discussions
3. https://connect.topcoder-dev.com/projects/591/discussions
4. Create new discussion topic **Lets Discuss** And post word **Discussion**(See screenshot)
5. Post it using post button
6 Again try to post word **Discussion** one more time under topic **Lets Discuss**.

### Expected Result ###

Word Discussion is posted 

### Actual  Result ###

Sometimes there is error on page as screenshot
Sometimes no action is taken and word is not posted users post is lost

### Screenshots ###

*Paste screenshots here.*
When the user enters same word as above:

![image](https://user-images.githubusercontent.com/29735376/36351303-956209a2-149f-11e8-8e17-3760f7484988.png)

### Issue Information ###

Frequency: Always
Device: Desktop

OS: Win 10

Browser: Edge

**Comment by sdgun** [comment]
https://www.screencast.com/t/Jo9uu3tEyJ

**Comment by gargsaurabh86** [comment]
@sdgun Sorry if I'm confusing in steps,Here is video recording.

https://youtu.be/oPow5YBeLQY

Best Regards

**Comment by sdgun** [comment]
```
Failed to load resource: the server responded with a status of 502 (Bad Gateway)
/projects/591/discussions:1 Failed to load https://api.mixpanel.com/decide/?verbose=1&version=1&lib=web&token=07c0e5520b4b91ded181db0698edd705&ip=1&_=1519307261754: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://connect.topcoder-dev.com' is therefore not allowed access. The response had HTTP status code 502.
2api.mixpanel.com/decide/?verbose=1&version=2&lib=web&token=07c0e5520b4b91ded181db0698edd705&distinct_id=40152855&ip=1&_=1519307261760 Failed to load resource: the server responded with a status of 502 (Bad Gateway)
/projects/591/discussions:1 Failed to load https://api.mixpanel.com/decide/?verbose=1&version=2&lib=web&token=07c0e5520b4b91ded181db0698edd705&distinct_id=40152855&ip=1&_=1519307261760: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://connect.topcoder-dev.com' is therefore not allowed access. The response had HTTP status code 502.
api.topcoder-dev.com/v4/topics/2714/posts Failed to load resource: the server responded with a status of 422 ()
main.e781634f18736872f4b2.js:35 Uncaught (in promise) Error: Request failed with status code 422
    at e.exports (https://connect.topcoder-dev.com/main.e781634f18736872f4b2.js:35:191905)
    at e.exports (https://connect.topcoder-dev.com/main.e781634f18736872f4b2.js:67:83600)
    at XMLHttpRequest.p.(anonymous function) (https://connect.topcoder-dev.com/main.e781634f18736872f4b2.js:35:191052)
```
