### ISSUE TITLE
Error sharing latest project update with team

### ISSUE THREAD

**Issue by gargsaurabh86** [topcoderinc/connect-test-cycle-1#95]
### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/273

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_copilot/topcoder123
2. Select Active filter
3. Select my amazing application project i.e. https://connect.topcoder-dev.com/projects/273
4. Enter "test" Share the latest project update with team
5. Click Post button

### Expected Result ###

Latest project update is posted

### Actual  Result ###

Error on page is shown

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36346422-2ce40376-1436-11e8-8c4f-5bea2b54c519.png)
![image](https://user-images.githubusercontent.com/29735376/36346430-714c0180-1436-11e8-8fd9-1c7c84cf3046.png)
![image](https://user-images.githubusercontent.com/29735376/36346436-80cdf172-1436-11e8-896b-53817bd74151.png)

### Issue Information ###

Frequency: *how often the issue occurs*

Device: *device used for testing*

OS: *operating system used on test*

Browser: *browser and version used on test*

**Comment by sdgun** [comment]
This is because of test data issue, https://connect.topcoder-dev.com/projects/273 is an old project. For new projects this won't happen

**Comment by gargsaurabh86** [comment]
@sdgun please check I raised this issue before #175 .
Also please check project id in the first screenshot is 2346.
Thank you.

**Comment by sdgun** [comment]
```
POST https://api.topcoder-dev.com/v4/topics/ 500 ()
main.e781634f18736872f4b2.js:35 Uncaught (in promise) Error: Request failed with status code 500
    at e.exports (https://connect.topcoder-dev.com/main.e781634f18736872f4b2.js:35:191905)
    at e.exports (https://connect.topcoder-dev.com/main.e781634f18736872f4b2.js:67:83600)
    at XMLHttpRequest.p.(anonymous function) (https://connect.topcoder-dev.com/main.e781634f18736872f4b2.js:35:191052)
e.exports @ main.e781634f18736872f4b2.js:35
e.exports @ main.e781634f18736872f4b2.js:67
p.(anonymous function) @ main.e781634f18736872f4b2.js:35
Promise.then (async)
(anonymous) @ main.e781634f18736872f4b2.js:67
dispatch @ main.e781634f18736872f4b2.js:62
(anonymous) @ main.e781634f18736872f4b2.js:52
(anonymous) @ main.e781634f18736872f4b2.js:62
(anonymous) @ main.e781634f18736872f4b2.js:67
(anonymous) @ main.e781634f18736872f4b2.js:62
value @ main.e781634f18736872f4b2.js:129
value @ main.e781634f18736872f4b2.js:16
r @ main.e781634f18736872f4b2.js:21
a @ main.e781634f18736872f4b2.js:21
s @ main.e781634f18736872f4b2.js:21
p @ main.e781634f18736872f4b2.js:16
m @ main.e781634f18736872f4b2.js:16
r @ main.e781634f18736872f4b2.js:35
processEventQueue @ main.e781634f18736872f4b2.js:16
r @ main.e781634f18736872f4b2.js:62
handleTopLevel @ main.e781634f18736872f4b2.js:62
i @ main.e781634f18736872f4b2.js:62
perform @ main.e781634f18736872f4b2.js:16
batchedUpdates @ main.e781634f18736872f4b2.js:62
i @ main.e781634f18736872f4b2.js:16
dispatchEvent @ main.e781634f18736872f4b2.js:62
5main.e781634f18736872f4b2.js:129 
```

**Comment by vic-georgiev** [comment]
There's also a posting limit to the development server which is not present in production. This might block posting ability if we push too hard the dev server.
